version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - echo "Installing dependencies - `pwd`"
      - cd app && npm install
      - echo "dependencies install completed `date`"

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      # - npm test
  build:
    commands:
      - cd ..
      # Use AWS SAM to package the application using AWS CloudFormation
      - echo "Starting build `date` in `pwd`"
      #- printf "Listing directory \n `ls -lof`"
      - aws cloudformation package --template-file app-sam.yaml --s3-bucket $S3_BUCKET --output-template-file app-output_sam.yaml
      - aws cloudformation package --template-file test-sam.yaml --s3-bucket $S3_BUCKET --output-template-file test-output_sam.yaml
  post_build:
    commands:
      - echo "build completed on `date` artifacts uploaded to `echo $S3_BUCKET`"
artifacts:
  type: zip
  files:
    - app-output_sam.yaml
    - test-output_sam.yaml
  discard-paths: yes
